// Canonical event type strings — from docs/02-domain-model.md
// These are the only valid values for learning_events.event_type
export const LEARNING_EVENTS = {
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_PROCESSING_STARTED: 'DOCUMENT_PROCESSING_STARTED',
  DOCUMENT_PROCESSING_COMPLETED: 'DOCUMENT_PROCESSING_COMPLETED',
  DOCUMENT_PROCESSING_FAILED: 'DOCUMENT_PROCESSING_FAILED',

  LESSON_STARTED: 'LESSON_STARTED',
  LESSON_COMPLETED: 'LESSON_COMPLETED',
  LESSON_SECTION_VIEWED: 'LESSON_SECTION_VIEWED',

  QUIZ_STARTED: 'QUIZ_STARTED',
  QUIZ_COMPLETED: 'QUIZ_COMPLETED',
  QUIZ_QUESTION_ANSWERED: 'QUIZ_QUESTION_ANSWERED',

  FLASHCARD_REVIEWED: 'FLASHCARD_REVIEWED',
  FLASHCARD_SESSION_COMPLETED: 'FLASHCARD_SESSION_COMPLETED',

  CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
  CHAT_CITATION_CLICKED: 'CHAT_CITATION_CLICKED',

  EXAM_STARTED: 'EXAM_STARTED',
  EXAM_COMPLETED: 'EXAM_COMPLETED',

  AUDIO_GENERATION_STARTED: 'AUDIO_GENERATION_STARTED',
  AUDIO_GENERATION_COMPLETED: 'AUDIO_GENERATION_COMPLETED',
  AUDIO_PLAYBACK_STARTED: 'AUDIO_PLAYBACK_STARTED',
  AUDIO_QUIZ_INTERRUPTED: 'AUDIO_QUIZ_INTERRUPTED',

  SYLLABUS_GENERATED: 'SYLLABUS_GENERATED',
  SYLLABUS_UPDATED: 'SYLLABUS_UPDATED',
  LESSON_STALENESS_FLAGGED: 'LESSON_STALENESS_FLAGGED',

  CONCEPT_MASTERY_UPDATED: 'CONCEPT_MASTERY_UPDATED',
  CONCEPT_MASTERED: 'CONCEPT_MASTERED',

  JOB_STARTED: 'JOB_STARTED',
  JOB_PROGRESS: 'JOB_PROGRESS',
  JOB_COMPLETED: 'JOB_COMPLETED',
  JOB_FAILED: 'JOB_FAILED',
} as const

export type LearningEventType = (typeof LEARNING_EVENTS)[keyof typeof LEARNING_EVENTS]
